#! /bin/bash


cd ../../../netineti/
python neti-server.py &
cd ../webservices/ruby/
ruby taxon_finder_web_service.rb &

# # reconciliation
# cd ../../../reconciliation/
# python recons_server.py &
# ruby reconcile_web_service.rb -p 3000 &

cd ../demo_clients/Facade_demo_for_neti_and_reconciliation/



ruby names_tools.rb -p 3001 &
