#! /bin/bash

# laptop
# tools_dir=/Users/ashipunova/code/web_serv_sci_names/name_tools
tools_dir=/Users/anna/work/sinatra/Web-Service-for-names-tools

cd $tools_dir/py_server/
python L-server-test.py &
python recons_server.py &
cd $tools_dir/webservices/
ruby taxon_finder_web_service.rb &
ruby reconcile_web_service.rb -p 3000 &
cd $tools_dir/sinatra/
ruby names_tools.rb -p 3001 &
