#! /bin/bash


cd /Users/anna/work/web_services/under_svn/new/netineti
python neti-server.py &

cd /Users/anna/work/web_services/under_svn/new/webservices/ruby/trunk
ruby taxon_finder_web_service.rb &

# reconciliation
#cd ../../reconciliation/py-server/
#python recons_server.py &
#cd ../webservice
#ruby reconcile_web_service.rb -p 3000 &

cd /Users/anna/work/web_services/under_svn/new/webservices/demo_clients/neti_reconciliation_demo/trunk
ruby names_tools.rb -p 3001 &
