#! /bin/bash


cd ../../../../netineti/trunk/
python neti-server.py &

cd ../../webservices/trunk/ruby/
ruby taxon_finder_web_service.rb &

# reconciliation
#cd ../../reconciliation/py-server/
#python recons_server.py &
#cd ../webservice
#ruby reconcile_web_service.rb -p 3000 &

cd ../../webservices/trunk/demo_clients/neti_reconciliation_demo
ruby names_tools.rb -p 3001 &
